### ISSUE TITLE
Dynamic process

### ISSUE THREAD

**Issue by sleipnir** [alfetahe/process-hub#3]
Hello, first I would like to congratulate you on the excellent library. Not only in terms of the library but also for the excellent source code.

My question is whether it would be possible to start a process dynamically with ProcessHub. The use case would be to be able to start processes at any time during the execution of the program, that is, at runtime, not compile time. Example: the application receives a user request and we create a process with the user id as part of its identifier.
Currently this would be achieved in Elixir using a DynamicSupervisor. Would this be possible with ProcessHub?

Thanks!

**Comment by alfetahe** [comment]
Yes, this is possible. In fact, ProcessHub is designed this way. The system expects processes to come and go during runtime.

And thank you for your feedback!

**Comment by sleipnir** [comment]
Thank you @alfetahe
