### ISSUE TITLE
Variations on the global theme

### ISSUE THREAD

**Issue by MarthinL** [alfetahe/process-hub#4]
Hi,

Based on my fairly exotic use-case someone referred me to your project as being of possible interest. 

Going by your descriptions it would seem in your frame of reference the term **gobal** roughly equates **cluster** as in the  collection of linked instances of the Erlang VM running on (hopefully) seperate (LAN connected) hosts that are allowed to call on each other because they have the same cookie value. 

My use-case differs from yours (I think) in that my **global** is the multitude of geographically dispersed clusters of nodes my app runs orchestrated by generic Kubernetes. The purpose is to give the app requisite capacity by spreading the network access, business logic and database access around to be as close to the end-user as possible. 

I've designed my application's database from the ground up to be regionally distributed. I handle replication and updates required at the applicatin level, meaning each cluster runs a local HA database with some additional read replicas but the different databases do not talk to each other directly, only via the app. 

For the application to contact its peers via each other's public IP routed to a HTTP API is possible provided I can properly secure the connections with mutual TLS. But I'm looking at potentially better options whereby the inter-cluster calls can happen at the Erlang/Elixir level rather than via HTTP. I'm really looking for the simplest abstraction possible. I read the region id for each record a user retrieves directly from the database so I know which region to request it from and I'd like to make it a single call to some smart agent to fetch the data I need from their master regions. 

When the're just one region per continent network latency and bandwidth already clashes with the LAN-tyle assumptions made by Erlang VM style clustering which by default is fully meshed. When those continents each break down into several hundred regions, the full mesh approach collapses under the weight of its own overheads. Technically though any region could request data from any other region, which suggests full mesh functionality even when it doesn't really implement a full mesh. 

I'd hope to implement a different topology such as a hub-and-spoke topology or a sparse mesh based on what requests are actually flowing between regions in real time, like one would manage connection pools or cache, but contain all that complexity behind a simple inter-cluster/region request for data or updates getting sent out. 

I'm reasonably certain that my use-case and the approach I'm favouring at the moment falls outside the current scope and vision of your project. Would you have any interest in expanding your vision and project in that direction? Would you let me help you implement it or help me understand how you've put your project together so I can build what I need as a fork or a PR on top of what you've done? Or is it just too far outside your scope to consider?

 -- Thanks for your time -- Marthin Laubscher
 
 P.S. Together or separate, it's very likely whoever ventures in the direction I'm suggesting would seriously consider using [Partisan](https://github.com/lasp-lang/partisan) in the process.

**Comment by sleipnir** [comment]
Hello @MarthinL, I saw the description of your problem and I couldn't help but comment just out of curiosity that I implemented a topology very similar to your description in the [Spawn project](https://github.com/eigr/spawn).

Basically what we do is define a grouping, which we call [ActorSystem](https://github.com/eigr/spawn/blob/4c430aa724d4ec119e89987d92de30043ebe2242/examples/k8s/simple/system.yaml#L9), and within this grouping there can be N connected Erlang nodes.
Communication within the cluster works using Erlang Dist normally. But when you want to communicate with a different grouping we forward a message via [Nats broker to this grouping](https://github.com/eigr/spawn/blob/4c430aa724d4ec119e89987d92de30043ebe2242/lib/actors/actors.ex#L101). The [receiving cluster](https://github.com/eigr/spawn/blob/main/lib/spawn/cluster/node/server.ex) in turn will forward the message via Erlang Dist within its control region.

We do this in a transparent way for the user calling the Actor/Process. It doesn't need to know if the message was forwarded via Erlang Dist, Nats or any other way.

We use Horde to control the cluster, but we only use the distributed registry and not the supervisor as we have some affinity rules that need to be respected internally. So I'm looking at this excelent ProcessHub library to see if it could replace our internal Horde-based cluster implementation.

Maybe this could help in some way. I would also be happy if you took a look at our Spawn project and see if it would help you with anything. Or you may have some insight from these ideas to see how to proceed with your problem.

**Comment by alfetahe** [comment]
Hello!

Thank you for your interest!

Currently, I believe the library won't perform well in scenarios where nodes are geolocated around the world. There are some issues that need to be addressed, such as configurable timeouts or smart timeouts (which adjust themselves based on the current situation), and the system should handle situations better when messages are lost in communication.

As you mentioned, Erlang Distribution by default uses mesh topology, which is another hurdle to overcome with very large clusters, especially if nodes are geolocated around the world. To address such problems, I was thinking along similar lines as @sleipnir. We could have smaller "hubs" in each geolocation, each with its own unique `hub_id`, meaning it only controls processes within that hub and not other hubs. All hubs could then be connected using hidden nodes between them to create a communication channel between each regional hub. This way, we could avoid fully meshed connections, though it might introduce other issues.

This is just me thinking out loud :) I am open to other ways of addressing these problems as well. I'm interested in trying out ProcessHub-supported process management on Kubernetes-hosted clusters too if that makes any difference.

What ideas do you have regarding ProcessHub anyways? I can explain the code itself for you, but please keep in mind that it may still change a lot over time.

Even if your ideas are outside the scope of the ProcessHub library, I would still be interested in leaving room for integrations with other possible libraries.

**Comment by MarthinL** [comment]
One more thing. I'm fixing on launching my app soon but the initial version will run a the first few regions on the same LAN environment which keeps disterl on the table for the initial release. My plans are to introduce the abstraction now already with a trivial backend that maps straight onto disterl primitives. That would give me or us a stable definition to work against when we start taking things on board like mTLS, hidden node hierarchies, pooling, relays, least cost routing etc.

**Comment by sleipnir** [comment]
Excellent explanation of your use case and excellent analysis of your problem.

I was just wondering whether you agreed or disagreed with what we had suggested. Because I saw many similarities in what we said, without the same technical rigor (I don't think that was our intention anyway) and what you ended up describing.
For example, we said that a lot of it was about establishing limits on what was regional and what wasn't, and that if this was identifiable to the user then it would be simple to delegate the forwarding of the request to a non-mesh message passing mechanism, so that it was treated by the other region. At this point @alfetahe and I gave different implementation proposals, a pubsub or hidden nodes mechanism. Personally, I believe that hidden nodes would not work transparently over WAN, while pubsub mechanisms would be easier to implement over WAN.

Anyway, excellent discussion and if you are going to build something let me know as this is an area of ​​great interest on my part.

**Comment by MarthinL** [comment]
@sleipnir Yeah,
> I was just wondering whether you agreed or disagreed with what we had suggested. Because I saw many similarities in what we said, without the same technical rigor (I don't think that was our intention anyway) and what you ended up describing.

My intention wasn't to agree or disagree either, not yet anyway. My intent was and remains as stated to start a deep and meaningful conversation about how to frame or reframe the problem and as a result the solution. Only once we're on the exact same (and most likely new) page about how whatever solution we end up with fits into the context of a real-world distributed application can we start discussing technical details such as the validity and suitability of various options. 

To contextualise the above in terms of your example. You said a lot of it was about estblishing limits on what what regional and what wasn't. That's neither untrue nor helpful. A designer or team considering building a distributed solutions make nost of their mistakes in exactly that area and a lot of the reasons why has to do with distributed tools and frameworks aiming to be as generally applicable as they can and in the process offer no guidance either. The position I'm taking contradicts that approach saying that the way the solution delineates dsitribution boundaries should be be front and centrer in the problem domain or else it will end in tears. 

But then I go quite a bit further saying that from at least one real-life application's perspective that crucial real-world distribution delineator is the geographic distribution of people around the globe impacting on the network latency between their browsers/devices and the application's closest point of presence. I'd never claim any other application would have cause to solve the exact overall problem my app is aimed at solving, but I do think that firstly once it has been shown as a living example how a real-life problem such as where users find themselves in the world would be drawn all the way from reality into exactly what drives how the application distributes itself it will be a lot easier for others to treat their real-life distribution issues the same way. (Secondly) I also think that a well defined solution for distributing an application in line with the how its users are distributed geographically might well lead to a fair few application teams recognising that that they are facing the exact same real-life distribution issue to the extent that they don't even have to bring their own delineation factor but use the library as is. 

> At this point @alfetahe and I gave different implementation proposals, a pubsub or hidden nodes mechanism. Personally, I believe that hidden nodes would not work transparently over WAN, while pubsub mechanisms would be easier to implement over WAN.

We're not even properly brainstorming options yet, but if we were, your differing suggestions would both have to be considered along with others, each hopefully offering a way towards the overall goal. We'd do as we were taught, and formulate the best solution by drawing on all those ideas. But first we have to have clarity on what we're aiming to do.

I agree that hidden nodes isn't suitable for WAN. Actually as far as I can see, the entire disterl communication layer is limited to a LAN environment at best because the absense of encryption and the use of multicast makes it so. It is almost a given that to cross cluster (LAN) boundaries we will require a different transport. There are some established patterns for that in the form of Partisan and Submariner/Lighthouse, even in Istio and Linkerd, but like I've said each of those comes at a price (complexity, conflicting concepts, misaligned purposes, baggage built up in support of native environments with far less inherent support for distributed processing than Erlang/Elixir) that outweighs their value so we might end up taking the simplified version of that they do and make it so for ourselves. 

Thank you for participating in the conversation.

I'm especially open to suggestions as to a more suitable forum for this discussion than comments on an issue reported on a Github project. I remain hopeful that without me insisting on it that starting a fresh project focussed on this would emerge as everyone's preferred way forward. If I end up doing it alone I won't make it a separate project on Github but if we're going to all work on it together the proven way to do it is a project on Github. The only real question is whether or not this project has enough in common with the ProcessHub project to qualify as iether a sub-project or a new branch of the project or it would be better to see it as a standalone project? 

Comments and feedback please.

**Comment by alfetahe** [comment]
@MarthinL , first of all, great analysis on your part!

It seems that you are thinking more broadly, whereas ProcessHub is primarily focused on the distribution of processes. Your use case likely requires the distribution of various types of data, not just processes.

Currently, I don't have any major plans for extra functionality—not because I don't want to, but because the existing functionality already satisfies my project needs. However, I would love to see the library evolve into something even bigger.

While I am interested in extending the library for a wider range of distributed use cases, my current priority is to enhance the stability of the existing functionality. However, you are welcome to submit any pull requests or create issues on GitHub if you would like to add new features to the ProcessHub library.

I will also update the guides and provide a more detailed explanation of the overall architecture in the near future.

Additionally, I recommend looking into `riak-core`, as it may be useful for your needs.

**Comment by MarthinL** [comment]
@alfetahe, thanks for your kindness.

I've seen Riak and the misaligment was fairly obvious to me, but I'll have another look at the core part on its own to see if there's some alignment there. The primary misalignment isn't what you'd expect, i.e. that it's KV/NoSQL based or exposes my app to a whole new class of risks regarding data storage, backups and maintenance operations at scale. No, the main thing I found last time round was right there in their own summary of what Riak aims for (and I quote)

> Riak KV is a distributed NoSQL database designed to deliver maximum data availability by distributing data across multiple servers. As long as your Riak KV client can reach one Riak server, it should be able to write data.

which means their fundamental drivers are availability and load balancing across nodes and/or clusters that logiclly hold the same data and offer the same capabilities. Their fundamentals might suit some, even many, I'm sure, but it doesn't suit me. The big point of departure being that my regions are not each others' equals but each hold a unique subset of the total database. Similar concepts can be achieved with advanced configuration involving xCluster in YugabyteDB but it's right at the limits of what it can do and the baggage that one picks up from adopting that entire eco-system to support a single application adds up to a net loss.

> Currently, I don't have any major plans for extra functionality—not because I don't want to, but because the existing functionality already satisfies my project needs. However, I would love to see the library evolve into something even bigger.

I wouldn't mind learning more about your project and the needs ProcessHub solves for it. I've been fascinated of late by the variance in how distributed system approaches are getting applied in practice. I don't often see instances where people have had positive results from their attempts to spread large linear workloads over multiple machines and even fewer who had success over multiple WAN-connected clusters. To date, the only successes of the latter kind I've seen evidence of had been where the fundamental distribution is already present in the workload itself like in my case where the workload of serving a web-based user is relatively small the problem is that there are so many of them needing service at the same time and their geographic spread means no place on earth is equally or even suitably close to all users. 

Anyway, I think what I'll do is to formulate the facility I need specifically as a separate concern so that the interface between the Phoenix/Ecto/LiveView application and the inter-cluster communication mechanism can be clearly defined. It's good to mainain clear lines between separate concerns so it's not wasted effort to do that. Then I'll take that spec and write a trivial implementation of it using the relevnt parts of disterl using libcluster provides for. I.e. an initial version which defines the facility and how the application would specify what the nodes are and what the cost and limitations of each direct "link" between nodes are. 

I'll then put that as a separate repository on GitHub and invite people like yourself to consider bringing your insights and experiences from the work you've done into that project, or not. If nobody finds cause to join in and contribute, so be it, then the project will be either still-born or dormant until some time in the future when I am done with my solo implementation and can publish it as something that could add value to others. 

How does that sound?

**Comment by alfetahe** [comment]
> I'll then put that as a separate repository on GitHub and invite people like yourself to consider bringing your insights and experiences from the work you've done into that project, or not. If nobody finds cause to join in and contribute, so be it, then the project will be either still-born or dormant until some time in the future when I am done with my solo implementation and can publish it as something that could add value to others.

That sounds good!
